### PR TITLE
Updated README.md file

### PR DESCRIPTION
**Pull request by nicholas489**
## Description

This PR intends to make the following change:
- Updated the README.md file to properly describe our deliverable for Iteration 2

### CODE REVIEW

**Review by HamidRezaKhoram — COMMENTED** [review]
I love the attention to the details Nicholas!

**Comment by keitannunes** [comment]
LGBT

**Comment by keitannunes** [comment]
LGTM

**Review by keitannunes — APPROVED** [review]
LGTM

**Pull request merged**
